apiVersion: v1
kind: Pod
metadata:
  labels:
    purpose: volume-demo
  name: container-storage
spec:
  containers:
  - name: container-1
    image: "busybox:1"
    args:
      - /bin/sh
      - -c
      - touch dates.txt; while true; do sleep 10 ; echo "container-1">>dates.txt; date>>dates.txt; done
  - name: container-2
    image: "busybox:1"
    args:
      - /bin/sh
      - -c
      - touch dates.txt; while true; do sleep 10 ; echo "container-2">>dates.txt; date>>dates.txt; done
