apiVersion: v1
kind: Pod
metadata:
  labels:
    purpose: volume-demo
  name: host-path
spec:
  volumes:
     - name: common-storage
       hostPath:
         path: /host_mnt/c/Users/naray/test-mnt
  containers:
  - name: consumer
    image: "busybox:1"
    volumeMounts:
     - mountPath: /cache
       name: common-storage
    args:
      - /bin/sh
      - -c
      - cat /cache/test-file.txt
      - sleep 3600
